### PR TITLE
Missing spark deploy-mode argument

### PR DESCRIPTION
**Pull request by jackyoh**
Add deploy mode argument

### CODE REVIEW

**Comment by vanzin** [comment]
@jackyoh we can't merge patches if you don't sign a CLA. See the wiki page linked from the README. Also, please file bugs before sending patches so we can track what goes in. Finally, we don't want this feature. You can set this through the `conf` field in the request, and this is one of those setting that should be really hard to be overridden by users (it's even blacklisted by default, so you can't set it even through `conf`).

So, please close this PR.

**Comment by tc0312** [comment]
@jackyoh Would you mind explaining your use case? Do you have a particular use case that needs per session deploy mode?

**Comment by jackyoh** [comment]
I run Spark on the Apache Mesos

The below is the server configuration:

$SPARK_HOME/conf/spark-defaults.conf
```
spark.master    mesos://192.168.1.224:7077
spark.submit.deployMode cluster
```

$LIVY_HOME/conf/spark-blacklist.conf
```
#Disallow overriding the master and the deploy mode.
#spark.master
#spark.submit.deployMode
#Disallow overriding the location of Spark cached jars.
#spark.yarn.jar
#spark.yarn.jars
#spark.yarn.archive
```

$LIVY_HOME/conf/livy.conf
```
spark.submit.deployMode=cluster
```

Run Spark on Mesos 
```
$SPARK_HOME/sbin/start-mesos-dispatcher.sh --master mesos://192.168.1.224:5050
```
Run livy server
```
$LIVY_HOME/bin/livy-server
```

I try client connection to livy server
spark-examples-1.6.1-hadoop2.6.0.jar alread exists in HDFS root path

```
curl -X POST --data '{"file":"/spark-examples-1.6.1-hadoop2.6.0.jar","className":"org.apache.spark.examples.SparkPi"}' 
-H "Content-Type: application/json" 192.168.1.224:8998/batches

{"id":0,"state":"running","log":[]}
```

Check the result of id 0
```
curl 192.168.1.224:8998/batches/0/log|python -m json.tool

result:

{
    "from": 0, 
    "id": 0, 
    "log": [
        "Warning: Skip remote jar hdfs://apache-server-a1:9000/spark-examples-1.6.1-hadoop2.6.0.jar.", 
        "java.lang.ClassNotFoundException: org.apache.spark.examples.SparkPi", 
        "\tat java.net.URLClassLoader$1.run(URLClassLoader.java:366)", 
        "\tat java.net.URLClassLoader$1.run(URLClassLoader.java:355)", 
        "\tat java.security.AccessController.doPrivileged(Native Method)", 
        "\tat java.net.URLClassLoader.findClass(URLClassLoader.java:354)", 
        "\tat java.lang.ClassLoader.loadClass(ClassLoader.java:425)", 
        "\tat java.lang.ClassLoader.loadClass(ClassLoader.java:358)", 
        "\tat java.lang.Class.forName0(Native Method)", 
        "\tat java.lang.Class.forName(Class.java:274)", 
        "\tat org.apache.spark.util.Utils$.classForName(Utils.scala:174)", 
        "\tat org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:689)", 
        "\tat org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)", 
        "\tat org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)", 
        "\tat org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)", 
        "\tat org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)"
    ], 
    "total": 16
}
```

Spark deploy mode seem to run client mode


Sorry my english isn't good

Thanks.

**Comment by vanzin** [comment]
Support for `spark.submit.deployMode` in the configuration was only added in 2.0:
https://issues.apache.org/jira/browse/SPARK-10123

**Comment by vanzin** [comment]
If you really want to support that, I'd be sort of ok with translating the config value to a command line argument, so that this can be made to work with pre-2.0 Spark. That would be done in the RSC code (ContextLauncher.java), and needs to check both the user and the default configuration files (which are merged by the RSC).

But this should *not* be exposed as a session creation parameter (just like the master is not), for the reasons I mentioned before. This is not something the user should be able to control, and that's why it's in the blacklist, so that if set in the user's conf it triggers an error.

**Comment by jackyoh** [comment]
@vanzin Thank you, I close this PR.

**Pull request closed without merging**
