### PR TITLE
LIVY-310. Kinit should be called before doing recovery check

### PR DESCRIPTION
**Pull request by jerryshao**
Otherwise, the check will be failed with Kerberos exception.

CC @tc0312 @zjffdu .

### CODE REVIEW

**Comment by tc0312** [comment]
Thanks. Are there plans to add integration test for Kerberos?

**Comment by jerryshao** [comment]
@tc0312 it is not a trivial work to support kerberos for integration test, currently I don't have a plan on it.

@zjffdu , can you please take a look, thanks a lot.

**Comment by zjffdu** [comment]
LGTM, yeah I don't think it is easy to test kerberos. @jerryshao did you manually test it ?

**Comment by jerryshao** [comment]
Yes.

**Comment by tc0312** [comment]
I'm merging this now but we really need integration test for Kerberos.

**Pull request merged**
