### PR TITLE
LIVY-271. Fixed repl session to return traceback as a JSON list in error cases.

### PR DESCRIPTION
**Pull request by zjffdu**
traceback could be json list or json object which is misleading. So this PR would not include traceback when it is null. 

Tested manually.

### CODE REVIEW

**Comment by zjffdu** [comment]
@tc0312 @jerryshao Please help review

**Comment by jerryshao** [comment]
LGTM.

**Comment by tc0312** [comment]
Traceback should always be a JSON List.
Mind if you provide a repro when it returns a JSON Object? Let's fix that bug instead of this.

**Comment by zjffdu** [comment]
If you send code "sc.", you will get the following output. 
```
{
  "total_statements": 1,
  "statements": [
    {
      "id": 0,
      "state": "available",
      "output": {
        "status": "error",
        "execution_count": 0,
        "ename": "Error",
        "evalue": "incomplete statement",
        "traceback": {}
      }
    }
  ]
}
```

After this PR, we could get
```
    {
      "id": 1,
      "state": "available",
      "output": {
        "status": "error",
        "execution_count": 1,
        "ename": "Error",
        "evalue": "incomplete statement"
      }
    }
```

**Comment by tc0312** [comment]
Can we fix that to return `[]` instead? This PR will break Jupyter integration.

**Comment by zjffdu** [comment]
@tc0312 I just pushed a new commit to return [] for empty traceback.
```
{
  "total_statements": 1,
  "statements": [
    {
      "id": 0,
      "state": "available",
      "output": {
        "status": "error",
        "execution_count": 0,
        "ename": "Error",
        "evalue": "incomplete statement",
        "traceback": []
      }
    }
  ]
}
```

**Comment by tc0312** [comment]
Thank you. Will merge once test passes.

**Pull request merged**
