### PR TITLE
LIVY-218. Updating link to download build 0.3.0

### PR DESCRIPTION
**Pull request by jonalter**
[LIVY-218](https://issues.cloudera.org/browse/LIVY-218)

### CODE REVIEW

**Comment by ksakellis** [comment]
@jonalter I received your name on the CCLA but have not yet gotten a signed ICLA from you: 
https://github.com/cloudera/livy/wiki/Individual-Contributor-License-Agreement-(ICLA). Please either sign and email cla@cloudera.com a copy or fax it.

**Comment by jonalter** [comment]
Thanks @ksakellis I just sent the email.

**Comment by ksakellis** [comment]
@jonalter thanks!

**Comment by tc0312** [comment]
@ksakellis Please give us the greenlight when we can merge this. Thanks!

**Comment by ksakellis** [comment]
@tc0312 go for it!

**Pull request merged**
