### PR TITLE
LIVY-352. Web UI. Added pagination by updating to use JQuery DataTables

### PR DESCRIPTION
**Pull request by ajbozarth**
[LIVY-352](https://issues.cloudera.org/browse/LIVY-352)

Followup to #319 adding pagination and search by switching to use jQuery DataTables like the Spark Web UI.

none
both
sessions
batch

### CODE REVIEW

**Comment by ajbozarth** [comment]
@zjffdu could you take a look at this and #327 since you requested these additions

**Comment by ajbozarth** [comment]
@jerryshao could you also review this too?

**Comment by jerryshao** [comment]
Sorry I'm not familiar with JQuery, trying to understand it 😄 .

LGTM from my poor knowledge of JS.

**Comment by jerryshao** [comment]
Hi @ajbozarth , sorry for the delay, can you submit this PR against https://github.com/apache/incubator-livy, thanks.

**Comment by ajbozarth** [comment]
Moved to https://github.com/apache/incubator-livy/pull/3

**Pull request closed without merging**
