### PR TITLE
LIVY-302 - Fail to parse Spark version when including "-SNAPSHOT"

### PR DESCRIPTION
**Pull request by purechoc**
add spark version check case : spark version is 2.0.3-SNAPSHOT

### CODE REVIEW

**Comment by tc0312** [comment]
I think this addresses https://github.com/cloudera/livy/pull/180 too.

**Comment by jerryshao** [comment]
@purechoc , can you also add test for cloudera related version number (like `1.5.0-cdh5.5.2`)? Others LTGM.

**Comment by purechoc** [comment]
add test for CDH related

**Comment by tc0312** [comment]
Merging to master and branch-0.3.

**Pull request merged**
